"""
Django settings for videoextraction project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GOOGLE_OAUTH_CREDENTIALS = os.path.join(BASE_DIR, "credentials.json")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-i74&q2y37u8h-qdk4w@t7+&ukr)mu8^p1xr59i5z7_91fyb84+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'extractionapp',
    'adminapp',
    'sslserver',
    'django_extensions',
    'corsheaders',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_AGE = 60 * 60 * 24  # 1 day
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # Ensure sessions are not expired when the browser is closed
SESSION_COOKIE_SECURE = False  # Set to True in production with HTTPS
# SESSION_COOKIE_HTTPONLY = True
SESSION_SAVE_EVERY_REQUEST = True
CSRF_TRUSTED_ORIGINS = ['https://localhost:8000']
SESSION_COOKIE_SAMESITE= 'Lax'  # Allow cookies for same-site navigation
SESSION_COOKIE_DOMAIN = None     # Default for localhost

ROOT_URLCONF = 'videoextraction.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'videoextraction.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'videoSEODB',  # Your database name
        'USER': 'postgres',        # Your database username
        'PASSWORD': '1234',    # Your database password
        'HOST': 'localhost',            # Set to empty string for localhost
        'PORT': '5432',                 # Default PostgreSQL port
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}


OPENAI_API_KEY = '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'
# Whisper model settings


API_CONFIG = {
    'api_key': 'AIzaSyBPA3t8c4dWtwmXvm4JWa4tyXEYXNDtvo8',
    'cache_timeout': 60 * 15,  # Cache for 15 minutes
    'whisper_model' : 'base' 
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
        },
        '__main__': {  # Your logger
            'handlers': ['console'],
            'level': 'INFO',
        },
    },
}
# You can set this key directly or use environment variables
YOUTUBE_API_KEY = os.getenv('YOUTUBE_API_KEY', 'AIzaSyBPA3t8c4dWtwmXvm4JWa4tyXEYXNDtvo8')

RAZORPAY_API_KEY = "rzp_test_0XYpYSiR8V6hyh"
RAZORPAY_API_SECRET = "toACX9h93ixCjX11NBFNCaHn"

SCRAPY_PROJECT = 'trends'  # Scrapy project name
SCRAPY_SETTINGS_MODULE = 'trends.settings'  # Path to Scrapy settings

CORS_ALLOWED_ORIGINS = [
    "https://studio.youtube.com",
    "https://localhost:8000",

     "https://ada3-103-161-55-72.ngrok-free.app"
                 
]
CORS_ALLOW_ALL_ORIGINS = True
CSRF_TRUSTED_ORIGINS = [
    "https://studio.youtube.com",
    "http://127.0.0.1:9000",
   
     "https://ada3-103-161-55-72.ngrok-free.app"
    
]
ALLOWED_HOSTS = ["127.0.0.1", 
                 "localhost", 
                 "studio.youtube.com",
                 "6115-103-161-55-15.ngrok-free.app",  # Add your ngrok URL here
                 "ada3-103-161-55-72.ngrok-free.app"
                 ]

