# Generated by Django 5.1.2 on 2024-10-30 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractionapp', '0002_alter_keyword_keyword_alter_keyword_search_volume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='search_volume',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
