# Generated by Django 5.1.2 on 2024-11-02 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractionapp', '0003_alter_keyword_search_volume'),
    ]

    operations = [
        migrations.CreateModel(
            name='videoSEODB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='media/videos/')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('tags', models.TextField()),
                ('keywords', models.TextField()),
            ],
        ),
    ]
