# Generated by Django 5.1.2 on 2024-11-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractionapp', '0004_videoseodb'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoseodb',
            name='base_file_name',
            field=models.CharField(default='unknown_video.mp4', max_length=255),
        ),
    ]
