# Generated by Django 5.1.2 on 2024-11-02 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractionapp', '0006_urlseodb'),
    ]

    operations = [
        migrations.CreateModel(
            name='keywordSEODB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('tags', models.TextField()),
                ('keywords', models.TextField()),
            ],
        ),
    ]
