# Generated by Django 5.1.2 on 2024-11-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractionapp', '0007_keywordseodb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlseodb',
            name='title',
            field=models.TextField(),
        ),
    ]
