# Generated by Django 5.1.2 on 2024-11-14 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extractionapp', '0011_usergoal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergoal',
            name='user',
        ),
    ]
