# Generated by Django 5.1.2 on 2024-11-14 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractionapp', '0012_remove_usergoal_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(max_length=50)),
                ('goal', models.CharField(max_length=100)),
                ('Discovery', models.CharField(max_length=100)),
            ],
        ),
    ]
