# Generated by Django 5.1.2 on 2024-11-14 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extractionapp', '0013_discovery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discovery',
            old_name='Discovery',
            new_name='discovery',
        ),
    ]
