# Generated by Django 5.1.2 on 2024-11-16 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractionapp', '0018_contactform_order_id_contactform_payment_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('signature', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='contactform',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='contactform',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='contactform',
            name='signature',
        ),
    ]
