# Generated by Django 5.0.6 on 2024-11-30 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractionapp', '0020_contactform_authentication_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubeuser',
            name='free_trial_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
