# Generated by Django 5.0.6 on 2024-11-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractionapp', '0021_youtubeuser_free_trial_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubeuser',
            name='trial_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Expired', 'Expired')], default='Active', max_length=20),
        ),
    ]
