# Generated by Django 5.0.6 on 2024-11-30 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractionapp', '0022_youtubeuser_trial_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubeuser',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
