# Generated by Django 5.0.6 on 2024-11-30 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractionapp', '0023_youtubeuser_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubeuser',
            name='role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
