# Generated by Django 5.0.6 on 2024-11-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractionapp', '0024_youtubeuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubeuser',
            name='discovery',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='youtubeuser',
            name='goal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
