# Generated by Django 5.0.6 on 2024-12-05 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractionapp', '0025_youtubeuser_discovery_youtubeuser_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubeuser',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='youtubeuser',
            name='payment_plan',
            field=models.CharField(blank=True, choices=[('Basic', 'Basic'), ('Standard', 'Standard'), ('Premium', 'Premium')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='youtubeuser',
            name='payment_term',
            field=models.CharField(blank=True, choices=[('Yearly', 'Yearly'), ('Monthly', 'Monthly')], max_length=10, null=True),
        ),
    ]
