# Generated by Django 5.0.6 on 2024-12-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractionapp', '0026_youtubeuser_amount_youtubeuser_payment_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubeuser',
            name='currency',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
