# Generated by Django 5.0.6 on 2024-12-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractionapp', '0030_alter_affiliateuser_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliateuser',
            name='user_logged_in_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
