# Generated by Django 5.0.6 on 2024-12-07 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractionapp', '0031_affiliateuser_user_logged_in_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliateuser',
            name='channel_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='affiliateuser',
            name='free_trial_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='affiliateuser',
            name='trial_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Expired', 'Expired')], default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='affiliateuser',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='affiliateuser',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
