# Generated by Django 5.0.6 on 2024-12-08 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractionapp', '0033_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('youtube_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extractionapp.youtubeuser')),
            ],
        ),
    ]
