# Generated by Django 5.0.6 on 2024-12-08 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractionapp', '0034_subscription_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_term',
            field=models.CharField(blank=True, choices=[('Yearly', 'Yearly'), ('Monthly', 'Monthly')], max_length=20, null=True),
        ),
    ]
