# Generated by Django 5.0.6 on 2024-12-08 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractionapp', '0035_payment_payment_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='extractionapp.subscription_data'),
        ),
        migrations.AddField(
            model_name='subscription_data',
            name='razorpay_subscription_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='subscription_data',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled')], default='active', max_length=20, null=True),
        ),
    ]
